- project:
    name: openstack/compute-hyperv
    check:
      jobs:
        - build-openstack-releasenotes
        - build-openstack-sphinx-docs
    gate:
      jobs:
        - build-openstack-releasenotes
        - build-openstack-sphinx-docs
